# Generated by Django 3.0.4 on 2020-04-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200406_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
